# Generated by Django 5.0.1 on 2024-02-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
