# Generated by Django 5.0.1 on 2024-08-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='team',
            field=models.CharField(default='Design', max_length=30),
        ),
    ]
