# Generated by Django 5.0.1 on 2024-08-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0004_employee_photo_employee_status_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(default='Active', max_length=30),
        ),
    ]
